### ISSUE TITLE
Implement danger zone

### ISSUE THREAD

**Issue by ItsALie** [bcitdatacomm/game#27]
Create and shrink the danger zone
See Shrink Danger Zone Pseudocode
https://docs.google.com/document/d/1hOUWyDaES2KyRVVhkWPAtfL-4nF97YO2QJ41akT9i6U/edit?usp=sharing

**Comment by tehp** [comment]
@ItsALie is it confirmed that we will close at a constant rate to force the game to end by a certain point? Can't find this anywhere.

**Comment by ItsALie** [comment]
@tehp It was never discussed in detail. The code I wrote does a constant decrease to simulate creeping in on the players, but could be modified however we want.
Its something everyone needs to agree on.
