### ISSUE TITLE
Name ideas!

### ISSUE THREAD

**Issue by tehp** [bcitdatacomm/game#3]
Post your name ideas below, use reactions to mark the ones that you like the most. 👍

**Comment by jctee** [comment]
wild west with spells

**Comment by ItsALie** [comment]
Spurs & Spells

**Comment by OPwonShinobi** [comment]
Wands & Winchesters

**Comment by tehp** [comment]
King of the Plains

**Comment by OPwonShinobi** [comment]
family-friendly anime-style meet and fun, featuring cowboys and magic :gun: :shipit: :clock12: :sparkles: :sparkles: :sparkles:

**Comment by locria** [comment]
Mahou Cowgirls

**Comment by CanOSpam** [comment]
Spirits of the West

**Comment by CanOSpam** [comment]
Desperado
